#!/bin/bash -e
# Copyright (c) 2014 Heikki Hokkanen <hoxu at users.sf.net>
# License: GPLv3

git_dir=$(readlink -f $(git rev-parse --git-dir))
task_dir=$(git config --get gtw.repository || echo "$git_dir/task")
branch=$(git config --get gtw.branch || echo tasks)

function msg() {
	echo "gtw: $1" >&2
}

if [ ! -d "$task_dir" ]; then
	msg "taskwarrior repository not set up yet in $task_dir"
	if git show-ref --verify --quiet refs/heads/"$branch"; then
		msg "branch '$branch' exists in main repository, cloning"
		git clone "$git_dir" "$task_dir"
		git reset --hard origin/"$branch"
		git branch --set-upstream-to=origin/"$branch"
	else
		msg "branch '$branch' does not exist either, creating both"
		git init "$task_dir"
		# TODO initial commit?
		pushd "$task_dir" >/dev/null
		git remote add origin "$git_dir" # TODO use a relative path to allow moving parent repo?
		#git branch --set-upstream-to=origin/"$branch" master
		popd
	fi
else
	pushd "$task_dir" >/dev/null
	git pull --quiet --ff-only
	popd >/dev/null
fi

command="$*"

pushd "$task_dir" >/dev/null
TASKDATA="$task_dir" task $*
git add --all .
GIT_COMMITTER_NAME="gtw" \
GIT_COMMITTER_EMAIL="gtw@localhost" \
git commit --quiet -m "task $command"

git push --quiet -u origin master:$branch
