#!/bin/bash
set -e

gtw=$(readlink -f ./gtw)

function oneTimeSetUp() {
	tmpdir=$(mktemp -d)
}

function oneTimeTearDown() {
	if [ -n "$tmpdir" ]; then
		rm -rf "$tmpdir"
	fi
}

function setUp() {
	pushd "$tmpdir"
	mkdir repo
	cd repo

	git init
	git commit --allow-empty -m 'Empty repository.'
}

function tearDown() {
	popd
	rm -rf "$tmpdir/repo"
}

function commonAsserts() {
	assertEquals "Main repository tasks sha1 matches taskwarrior repository sha1" $(cat .git/refs/heads/tasks) $(cat .git/task/.git/refs/heads/master)
}

function testFreshRepo() {
	$gtw add test task
	$gtw add second task

	assertEquals "Wrong number of commits in tasks branch" 2 $(git rev-list tasks |wc -l)
	commonAsserts
}

function testRepoWithTasksBranch() {
	$gtw add test task

	rm -rf .git/task/

	$gtw long # should recreate repository

	commonAsserts

	$gtw add another task

	commonAsserts
}

. $(which shunit2)


